import { css } from "@emotion/core"
import React from "react"
import Helmet from "react-helmet"
import Twemoji from "react-twemoji"
import "../styles/tailwind.css"
import { TableOfContents, TOC } from "./blog/general/TableOfContents"
import { Stylable } from "./Components"
import SiteFooter from "./Footer"
import SiteHeader from "./Header"
import { BackgroundProps, Meta } from "./templates/templates"
import { PrimitiveBackground } from "./templates/PrimitiveBackground"
