= ドワンゴ見学エントリ

:page-path: dwango-event
:page-date: 2019-12-02
:page-status: public
:toc: left
:sectlinks:

株式会社ドワンゴさんを見学させていただくという機会がありました。3ヶ月経ってますがいまさら回顧します。

== なぜこうなったのか

* かつてドワンゴが運営していた**friends.nico**(フレニコ/ニコフレ)というSNS(Mastodonサーバー)
* フレニコのサービス終了のときにドワンゴCOOの**くりたしげたか**さんと知り合う高校生**ももつきゆきや**
* 高校生ドワンゴ見学イベントをやることになる
* フレニコ後継SNS**Best Friends**(ベスフレ)住民の関東の高校生ということで招集がかかる筆者**もみにす**

== 印象的なできごと

=== 東銀座駅と近すぎ

東銀座駅構内をうろちょろしてると入り口があるんですね。駅直結なので爆発させると銀座線日比谷線が止まると思われます。

あとビル(タワー？)を登る最中、7階にセブンイレブンがありました。狙ってるんでしょうか？

=== イベント中にニコる(α)が登場

すごくドワンゴらしい事象だと思います。Twitterを開いて栗田さんの送りたて告知ツイートを見てたりしました。PCプレ垢専用なので真っ先にニコるとかは無理でしたが。

=== 社員の方々

いろいろな社員さんが会議室にいらしていらしてお話しをしてくださったんですが、その数がすごく多いんです。
「これから出てくる社員の名札エリア」にたくさん名前があってちょっとビビったりしました。

印象に残ってるのは**ニコ厨率の高さ**でした。学生時代にニコニコを使っていて、ニコニコをよりよくしたくて…みたいな方が多かったです。でもこれすごくないですか？

https://www.nicovideo.jp/watch/sm9[sm9]が投稿されて12年、会議室1つ1つに割り当てられるほどバージョンアップを重ねて、いまや青春をニコニコに食べつくされた世代がニコニコの運営になってるんですよ。

あと大学で留年した、という話もすごい記憶に残ってます。「親が悲しむから留年はするな」と、先人たちからありがたいお言葉を頂きました。あっ、時報鳴りました。(12月03日です。あけましておめでとうございます)

== 反省会

自分は脳内反省会の主宰者として15年やってきましたが、いちばん大規模な反省会でしたね。現在進行形です。

=== 服が雑
* 真夏なので仕方がないといえばない
* 紫Tシャツ

=== 下準備不足
ゆきや君がニコニコオタク度を発揮し(すぎ)てて、自分はニコニコのことを全然知らなかったんだな…とか思いました。

あと、プログラミング周りの予習しとけばよかったです。今やってるようなことをあれの前に持ってこれたらネタになったかな～なんて後悔したり。

モンハンワールドが面白すぎたんですよね。時間期間の管理は絶対に改善しなきゃいけないポイントです。

== 感じたこととか思ったこととか

こういうIT企業に行くのは初めてでした。

普段なにげなく使っているサービスにも、向こう側には人がいるんですよってのを実感しました。 +
「1個人でない企業や団体に対しては多少ボコスカ言ったっていい」なんて考えか知りませんが、運営はエアプではないしサービス潰そうと思ってたりもしないんですね。運営はニコニコに情熱のある方々です。 

そういえば、窓口へのリプをSlackに投げて共有するとか、すばらしくかっこいいですよね。

帰ったあとにRECRUITページを見て給与にびっくりしたりしました。高校に届く求人票とか駄菓子に見えました。それと「ド社員ベ民の誰々に会えたかも」「その時まだ寝てた」なんて会話があったりしました。裁量労働制とかフレックスタイム制ってやつですか。朝起きなくていいのはうひょ～ってなるんですけど、その分自己管理力は求められますよね。責任を守った上での自由。

あと直接関係ないんですが、ドワンゴのあとにベスフレ民とオフったりしてました。そこでキャッシュレスの人はじめて見たんですよね。そっから僕はキャッシュレス沼に沈んでいくことになったんですよ。いまや懐かしい。

== さいごに…

あの日はこれまでの人生でいちばんヤバい日でした。ドワンゴに行って、たくさんの大人と話して、いろんな高校生と話して、恐るべき刺激を受けました。ゲームより先に持ってきたい趣味ができました。 +
最近はフロントエンドやりたいな～って思ってるのでJavaScriptやってます。Gatsbyを使ってこのブログを作りました。あとは、自己管理と能動性を高めることですね。なんか高校の課題研究でラズパイ使った人がいるらしく、その人に接触したいとか思ってます。 あと早く寝ます。がんばる。

今見たらだいたい2000文字ぐらい書いてることがわかりました。そんなものすごい体験の機会をお忙しい中くださったドワンゴ社員のみなさん、同年代として刺激をくれた高校生のみんな、すべての元凶の栗田さんとゆきや君、本当にありがとうございました！！




