= ドワンゴ見学エントリ

:page-path: dwango-event
:page-date: 2019-12-02
:page-status: public
:toc: left
:sectlinks:

株式会社ドワンゴさんを見学させていただくという機会がありました。3ヶ月経ってますがいまさら回顧します。

== なぜこうなったのか

* **friends.nico**というSNS(Mastodonサーバー)を、かつてドワンゴが運営していた
* サービス終了のときにドワンゴCOOの**くりたしげたか**さんと知り合う高校生**ももつきゆきや**
* ドワンゴ見学イベントをやることになる
* フレニコ後継SNS**Best Friends**勢の関東の高校生ということで招集がかかる筆者**もみにす**

== 行ってみてどうだったか

* 東銀座駅と近すぎ
* 7階にセブンイレブン
* きれいすぎ
** 適当な服で行ってわりと恥ずかしい思いしました

=== *イベント中にニコる(α)がリリース*

すごくドワンゴらしい事象だと思います。Twitterを開いて栗田さんの送りたて告知ツイートを見てたりしました。

=== 社員の方々

いろいろな社員さんが会議室にいらしていらしてお話しをしてくださったんですが、その数がすごく多いんです。
「これから出てくる社員の名札エリア」にたくさん名前があってちょっとビビったりしました。

印象に残ってるのは**ニコ厨率の高さ**でした。学生時代にニコニコを使っていて、ニコニコをよりよくしたくて…みたいな方が多かったです。でもこれすごくないですか？

https://www.nicovideo.jp/watch/sm9[sm9]が投稿されて12年、会議室1つ1つに割り当てられるほどバージョンアップを重ねて、いまや青春をニコニコに食べつくされた世代がニコニコの運営になってるんですよ。

あと大学で留年した、という話もすごい記憶に残ってます。「親が悲しむから留年はするな」と、先人たちからありがたいお言葉を頂きました。あっ、時報鳴りました。(12月03日です。あけましておめでとうございます)

== 反省会

自分は脳内反省会の主宰者として15年やってきましたが、いちばん大規模な反省会でしたね。現在進行形です。

=== 服が雑
* 真夏なので仕方がないといえばない
* 紫Tシャツ

=== 下準備不足
ゆきや君がニコニコオタク度を発揮し(すぎ)てて、自分はニコニコのことを全然知らなかったんだな…とか思いました。

あと、プログラミング周りの予習しとけばよかったです。今やってるようなことをあれの前に持ってこれたらネタになったかな～なんて後悔したり。

モンハンワールドが面白すぎたんですよね。時間期間の管理は絶対に改善しなきゃいけないポイントです。

== 感想

普段なにげなく使っているサービスにも、向こう側には人がいるんですよってことをわかった感があります。
どこどこが悪い、不便だとか批判するのはいいとして、運営はエアプだとかそういうのはだめですね。1個人でない企業や団体に対しては多少ボコスカ言ったっていいなどと思っても、やっぱりそれを見るのは1個人ですから。 +
[@niconico_talk]みたいな、フレンドリーというかフランクというかな公式アカウントは、そういう感じで人が見えるので好きです。

そういえば、窓口へのリプをSlackに投げて共有するとか、すばらしくかっこいいですよね。

帰ったあとにRECRUITページを見て給与にびっくりしたりしました。これを先に見てしまうと高校に届く求人票とか駄菓子に見えちゃいますね。それと「ド社員ベ民の誰々に会えたかも」「その時まだ寝てた」なんて会話があったりしました。裁量労働制とかフレックスタイム制ってやつですか。

永久機関じゃないですか。

